#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."
ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
if [ "$new_path" != "$old_path" ]
then
	if [ "$new_path" != "/" ]
	then
		ynh_replace_regex --match="#BASE_URL" --replace="BASE_URL=\"$new_path\"" --file="$install_dir/.env"
	else
		ynh_replace --match="BASE_URL" --replace="#BASE_URL" --file="$install_dir/.env"
	fi
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
